project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - research.qmd
    - career.qmd
    - publications.qmd
    - cv.qmd

website:
  title: "Dong-Joon Yi"
  navbar:
    background: "#f7f6f2"
    foreground: "#242e2b"
    collapse: false
    pinned: true
    left:
      - href: research.qmd
        text: Research
      - href: career.qmd
        text: Career
      - href: publications.qmd
        text: Publications
      - href: cv.qmd
        text: CV
  page-footer:
    left: "© Dong-Joon Yi"
    right: "iver.ydj@gmail.com"

format:
  html:
    theme: default
    mainfont: "Source Sans 3"
    fontsize: 17px
    smooth-scroll: false
    css: styles.css
    toc: false
    anchor-sections: true
    link-external-newwindow: true
    grid:
      body-width: 1080px
      margin-width: 0px
      sidebar-width: 0px
