project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - research.qmd
    - career.qmd
    - publications.qmd

website:
  title: "Dong-Joon Yi"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: career.qmd
        text: Career
      - href: publications.qmd
        text: Publications
  page-footer:
    left: "Dong-Joon Yi"

format:
  html:
    theme: darkly
    css: styles.css
    toc: false
    anchor-sections: true
    link-external-newwindow: true
    grid:
      body-width: 1080px
      margin-width: 0px
      sidebar-width: 0px
